sonar.projectKey=calculadora-react
sonar.projectName=Calculadora React App
sonar.sources=app,components,hooks,constants,scripts
# Excluimos node_modules y archivos de configuración de Expo que rompen el análisis de tipos
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.jsx,expo-env.d.ts,*.config.js,tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json