sonar.projectKey=calculadora-react
sonar.projectName=Calculadora React App
sonar.projectVersion=1.0

# Cambiamos 'src' por las carpetas reales de tu proyecto
sonar.sources=app,components,constants,hooks,scripts

# Exclusiones para no analizar archivos innecesarios
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js,package.json,package-lock.json

sonar.sourceEncoding=UTF-8

# Esto le indica al escáner ignorar los archivos de configuración de Expo
sonar.typescript.tsconfigPath=tsconfig.json