sonar.projectKey=calculadora-react
sonar.projectName=Calculadora React App
sonar.projectVersion=1.0

# FUENTES: Solo carpetas con código de la aplicación
sonar.sources=app,components,hooks,constants,scripts

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.node.maxspace=4096

# TESTS: Indicamos la nueva carpeta que creaste en la raíz
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.test.js,__tests__/**/*.test.jsx

sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.jsx

# COBERTURA: Ruta al reporte que genera Vitest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# CONFIGURACIÓN TS: Para que entienda los tipos de tu proyecto
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8